# Project information
site_name: Compustore
site_description: 'A GIS Stripe Project to demonstrate Payments and payment processor using good practices'
site_url: 'https://stephane-segning.github.io/compustore'

# Theme settings
theme:
  name: material
  locale: en
  highlightjs: true
  palette:
    scheme: slate
    primary: purple

# Navbar settings (site structure)
nav:
  - Home: README.md
  - Development:
      - Branching Concept: branching-strategy.md
      - SSDLC: SSDLC.md
      - Architecture: architecture.md
  - Storybook: storybook

# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

repo_name: Compustore
repo_url: https://github.com/stephane-segning/compustore
edit_uri: edit/main/docs/
